### ISSUE TITLE
Slow UI when having many portfolios and analyses

### ISSUE THREAD

**Issue by bbetov** [OasisLMF/OasisUI#227] opened 2020-06-03 17:03 UTC
We have a about 600 portfolios, most of them with a single analysis, some with two. 

Navigating the screens takes over 20-30 sec for each step most of the time. For example, after typing the username/password on the logon screen, the first screen appears after 10-15 seconds and then another 10-15 seconds for the portfolio table to show up.

Clicking on "Choose analysis" suffers the same issue. I see the screen after a few seconds, but the grid with the single analysis for that portfolio takes 20-30 secs to show up.

The API calls seem fast, although we have not done any comprehensive investigation. 

To make sure it is not a networking issue, we tested with a browser running on the same server.

**Comment by MattDonovan82** [comment] 2020-06-18 08:36
Seems like this is a UI issue as the API seems to be working ok. I'll assign to Nikki at Mirai.

**Comment by RolandASc** [comment] 2020-07-10 15:09
We have had a good look into what is typically happening in the UI, but I fear that is has not been sufficient for us to fully understand / reproduce the observed slowness.

There are a few things that we can try to clarify though, and then maybe we need to see how we can get more details about your case or **whether there is a possibility for us to hook a UI up to your server / API, such that we could do some profiling / debugging there directly**?

### 600+ portfolios
This shouldn't be any issue in itself, Shiny (DataTables) can handle much larger tables efficiently. We have in fact also done some checks with more than 600 portfolios but nothing much happened there.

### Login with username / password and loading of the "landing page"
This can take some time and is not unexpected, I would say 10+ seconds is possibly fairly normal here, since the application is pre-loading quite some information across many modules. **The main point that could be discussed / addressed in this context will be a re-occurring one, namely it has to do with the fundamental synchronous reactive application design that the UI has been designed with (which has always been perfectly suitable for Shiny). Shiny supports asynchronous programming since a while now, and it would be worth considering whether the OasisUI shouldn't be refactored in some places to make use of those concepts.** Of course such change wouldn't just be a fix and require a bit of effort, but it would be perfectly possible to do so incrementally and have some modules asynchronous and others synchronous side by side.

### 10-15 seconds for the portfolio table
This one is the hardest for me to understand, there really isn't much happening here in the background, and it lets me wonder whether your application is being burdened by some garbage that hasn't been cleared properly or anything of that sort. But I do assume that you have tried re-starting the UI, since you also did the test with the browser running on the same server?

### Clicking on "Choose analysis"
This step has grown a little with some extra things being processed for the exposure validation parts, so similar to the loading of the landing page after the login, it can take 5-10 seconds until everything is completed in the background and the table grid is fully displayed (which likewise could be shown much sooner if we would implement some futures/promises there).
If you are on the exposure validation map rather than the summary (in the bottom part), it can potentially take 20 sec and more to re-draw the map when you e.g. switch the portfolio in the respective control at the top of this second step's page.

### Conclusion
* we have an open topic about introducing some asynchronous concepts or making the application a little less "reactive" in certain areas.
* we don't fully understand what you are suffering from, and should potentially investigate further. To some degree it could be due to issues outside of the UI's reach, but it's impossible to say now.
* it would be good to get some more basic information about the system / setup with such issues, e.g. what kind of server, browser, version of the platform, etc., even if we don't have a knowledge base of known issues at this point.

**Comment by bbetov** [comment] 2020-07-10 15:20
Thank you very much for looking into this.
The server is a 48 core, 512GB RAM old HP DL780G6 and I am accessing it with Mozilla Firefox, but my colleagues are using Chrome.

Indeed, I agree it could be some of the security softwares and proxies that are required on our work machines. It is also possible that we had forgotten to clear up the shared files/database files. 

We had unfortunately reinstalled, but will try to reproduce. You can close this for now and I can re-open if I manage to reproduce it.

**Comment by nfarabullini** [comment] 2020-07-14 08:43
Issue closed due to further investigations

**Closed by nfarabullini** 2020-07-14 08:43 UTC
